### ISSUE TITLE
OpenRouter

### ISSUE THREAD

**Issue by jaim12005** [mark3labs/mcphost#1]
This is awesome!

Would you consider adding OpenRouter integration noting it supports MCP (Anthropic)?

Would be a big boon for those at the bottom tier API access.

**Comment by ezynda3** [comment]
I will look into this.

**Comment by jaim12005** [comment]
Thank you! Also - I think I commented on reddit but prompt caching would be amazing as well. 

I noted this thing was gobbling up tokens like crazy. 

I may make a fork and try to implement myself then well send a PR (can decide if you want to implement). 

Thanks for making this!

**Comment by ezynda3** [comment]
All PRs are welcome!

**Comment by ezynda3** [comment]
> Thank you! Also - I think I commented on reddit but prompt caching would be amazing as well.
> 
> I noted this thing was gobbling up tokens like crazy.
> 
> I may make a fork and try to implement myself then well send a PR (can decide if you want to implement).
> 
> Thanks for making this!

BTW just added a default message window of 10 messages so that should help a little bit with the context overloading

**Comment by ezynda3** [comment]
Fixed with #5
