### ISSUE TITLE
mcphost gets stuck when loading servers

### ISSUE THREAD

**Issue by epaproditus** [mark3labs/mcphost#2]
I tried using MCPHost, but when I receive a notification that the servers are loading, it always gets stuck on loading one of them. The issue seems random as it varies each time.

The error I get is:
```
abe@m1 ~ % mcphost
```
```
2024/12/10 22:44:03 info initializing server... name=filesystem
2024/12/10 22:44:05 info initializing server... name=todoist
2024/12/10 22:44:07 info initializing server... name=github
error: error creating mcp clients: failed to initialize mcp client for github: context deadline exceeded

Usage:
mcphost [flags]
mcphost [command]
```

**Comment by ezynda3** [comment]
The github server expects an environment variable which isn't supported in the mcphost config yet.

**Comment by ezynda3** [comment]
@epaproditus should work now.
